version: '3.7'

services: 
    postgres:
        image: 'postgres:12.3'
        volumes: 
            - 'postgres:/var/lib/postgresql/data'
        environment: 
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432:5432
        
    redis:
        image: 'redis:3.2-alpine'
        command: redis-server
        ports: 
            - '6379:6379'
        volumes: 
            - 'redis:/var/lib/redis/data'

    website:
        depends_on: 
            - postgres
            - redis
        build: .
        command: bash start.sh
        ports: 
            - '3000:3000'
        volumes: 
            - '.:/onebitchat'
            - 'box:/box'
        environment: 
            - BUNDLE_PATH=/box
            - DB_HOST=postgres
            - DB_USER=postgres
            - DB_PASS=postgres
    box:
        image: busybox
        volumes: 
            - box:/box

volumes: 
    redis:
    postgres:
    box: