default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST']%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: onebitchat_development
test:
  <<: *default
  database: onebitchat_test
production:
  <<: *default
  database: onebitchat_production
